<?php

namespace AppBundle\Repository;
use PDO;

/**
 * PlaceRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PlaceRepository extends \Doctrine\ORM\EntityRepository
{
    public function getCountOfPlaces()
    {
        $connection = $this->getEntityManager()->getConnection();
        $statement = $connection->prepare("SELECT COUNT(id) FROM places;");
        $statement->execute();
        return $result = $statement->fetchAll(PDO::FETCH_COLUMN);
    }
}
