<?php

namespace AppBundle\Repository;
use PDO;

/**
 * UserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserRepository extends \Doctrine\ORM\EntityRepository
{
    public function getCountOfUsers()
    {
        $connection = $this->getEntityManager()->getConnection();
        $statement = $connection->prepare("SELECT COUNT(id)FROM users;");
        $statement->execute();
        return $result = $statement->fetchAll(PDO::FETCH_COLUMN);
    }
}
